config/routes.rb
Ex2::Application.routes.draw do

  get 'n' => "site#test"

  get "w/:text" => "google_search#search"

  get 'm' => 'mobile#index_posts', :as=>:mobile_root
  scope 'm', :as=>'mobile' do
    get "mentions"  => 'mobile#index_mentions'
    get 'posts'     => 'mobile#index_posts'
    post 'new_post' => 'mobile#index_new_post'
    get  "login" => 'mobile#login'
    post "login" => 'mobile#post_login'
    get "u/:username" => 'mobile#user', :as=>:user
    get "p/:id"            => 'mobile#post', :as=>:post
    post 'p/comment_create' => 'mobile#post_comment_create', :as=>:post_comment_create
    get "c/:label"  => 'mobile#city'
  end

  get 'c/:label' => 'cities#show', :as=>:city_label
  resources :cities, :only=>[:show] do
    collection do
      get 'base_search'
    end
  end

  scope 'a' do
    resources :smiles
    resources :user_agents, :only=>:index
    get 'user_sessions' => "user_sessions#index", :as=>'xxx'
    resources :translations, :path=>'t', :only=>[:index, :edit, :update] do
      collection do
        put   '' => 'translations#edit_multiple'
        post  '' => 'translations#update_multiple'
      end
    end
  end

  get 's/who_we_are' => 'site#who_we_are', :as => :s_who
  get 's/suggest' => 'suggestions#new', :as => :s_suggest
  

  resources :suggestions, :except => [:edit, :update]
  resources :user_sessions, :except => [:index, :edit, :update]
  
  get "u/out"    => "user_sessions#destroy",         :as => :out
  get "u/in"     => "user_sessions#new",             :as => :in
  get "u/new"    => redirect("r/new")
  
  get "u/send_password/:base64_key" => "user_sessions#send_password", :as =>:send_password
  get "u/new_password/:username/:token" => "user_sessions#new_password", :as =>:new_password
  post "u/create_password" => "user_sessions#create_password", :as =>:create_password

  get   "r/new"       => "registration#new"
  get   "r/new"       => "registration#new",          :as => :new
  post  "r/new"       => "registration#new_post"
  get   "r/captcha"   => "registration#captcha"
  post  "r/captcha"   => "registration#captcha_post"
  
  get "r/after_register"           => "registration#after_register"
=begin
  get "registration/new_by_profile"
  get "registration/new_by_invitation"
  get "registration/new_by_profile_post"
  get "registration/new_by_invitation_post"
  get "registration/confirm_email"
  get "registration/new_password"
  get "registration/new_password_post"

=end
  get  "e/basic"    => "edit#basic"
  put  "e/basic"    => "edit#basic_put"
  get  "e/cities"   => "edit#cities"
  put  "e/cities"   => "edit#cities_put"
  get  "e/username" => "edit#username"
  put  "e/username" => "edit#username_put"
  get  "e/email"    => "edit#email"
  put  "e/email"    => "edit#email_put"
  get  "e/password" => "edit#password"
  put  "e/password" => "edit#password_put"
  
  get  "e/photo" => "edit#photo"
  post "e/photo" => "edit#photo_post"
  
  get  "e/theme" => "edit#theme"
  post "e/theme" => "edit#theme_post"
=begin
  constraints :subdomain => "m" do
    get "s(/:text)"                 => "site#mobile_search"
    get "s/posts/:post_type/:text"  => "site#mobile_posts"
    root :to                        => "home#mobile_index"
  end
=end
  root :to => "home#index"

=begin
  get "search/paginated"
  get "search/async_holder"
  get "search/async_ajax"
=end

  get "s(/:text)" => "search#async", :as => :s
  get "s/posts/:post_type/:text" => "search#posts", :as => :search_posts
  get "z(/:text)" => "search#paginated"
  get "h/posts_followings_all_latest" => "home#posts_followings_all_latest"
  get "h/posts_followings_all"    => "home#posts_followings_all"
  get "h/posts_followings_status" => "home#posts_followings_status",  :filter => Post::CATEGORY_STATUS
  get "h/posts_followings_image"  => "home#posts_followings_image",   :filter => Post::CATEGORY_IMAGE
  get "h/posts_followings_audio"  => "home#posts_followings_audio",   :filter => Post::CATEGORY_AUDIO
  get "h/posts_followings_other"  => "home#posts_followings_other",   :filter => Post::CATEGORY_OTHER
  get "h/posts_followers"         => "home#posts_followers"
  get 'h/ajax_notifications'           => "home#ajax_notifications"
  get 'h/ajax_news_button'        => "home#ajax_news_button"
  post 'h/invite'           => "home#invite"
  post 'h/mark_notifications_as_read'           => "home#mark_notifications_as_read"
  get 'h/ajax_suggestions_sidebar'  => 'users#ajax_suggestions_sidebar', :as=> :user_ajax_suggestions_sidebar
  

  resources :posts, :path => "p", :only => [:show, :destroy] do
    get "ajax_likes"
    post "like"
    get "ajax_comments"
    collection do
      get "generate_notifications"
      post "create_status"
      post "create_image"
      post "create_comment"
      get "ajax_search"
    end
  end
=begin
  devise_for :users do
    get "/u/out" => "devise/sessions#destroy",  :as => :out
    get "/u/new" => "devise/registrations#new", :as => :new
    get "/u/in"  => "devise/sessions#new",      :as => :in
  end
=end
  
  resources :users, :path => "u" do#, :only =>[:show, :index] do #, :index, :update do
    get :ajax_posts_all
    get :ajax_posts_status,  :filter => :status
    get :ajax_posts_image,   :filter => :image

    get :ajax_relations_following,  :filter => :following
    get :ajax_relations_follower,   :filter => :follower
    get :ajax_relations_friend,     :filter => :friend
    
    get :ajax_relations_sidebar_friend,     :filter => :friend
    
    get :likes
    get :ajax_relate_panel
    put :ajax_relate
  end
  get ":username" => "users#show", :as => "profile", :constraints => { :username => User::USERNAME_REGEX }
  scope ":username", :constraints => { :username => User::USERNAME_REGEX } do
    get 'followings'  => "relations#followings",  :as => :username_followings
    get 'followers'   => "relations#followers",   :as => :username_followers
    get 'friends'     => "relations#friends",     :as => :username_friends
  end

end

app/models/user.rb
class User < ActiveRecord::Base
      #cached_followings_user_ids    1,2,3,4,5
      #privileges_string             admin,spy,master
      #relations_count_string        followers:15,friends:3,followings:10,mentions:80
      #posts_count_string            status:15,image:3,audio:10,other:80,all:200

  #CONSTANTS

  #used in post_helper
  #USERNAME_REGEX_NOT = /[^a-zA-Z0-9_-]/
  #used in UsernameValidator and others
  #USERNAME_REGEX = /[a-zA-Z0-9_-]{2,}/
  USERNAME_REGEX = /[a-z0-9_]{2,}/i
  #used in EmailValidator
  EMAIL_REGEX = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  #NAME_REGEX = /^([0-9\^<,@\/\{\}\(\)\*\$%\?=>:\|;#]+)/ix


  
  include UserModuleAuthentication
  include UserModuleCustomize
  include UserModuleRelations
  include UserModuleKeyValueStore
  
  #VALIDATIONS

  validates :first_name,
  #          :format => {:with => NAME_REGEX },
            :presence => true, :length => { :in => 2..16 }
  validates :last_name,
            :presence => true, :length => { :in => 2..32 }
  
  #validate :custom_validations

  #def custom_validations
    #errors.add(:username, "username is not valid or is already taken") unless User.username_allowed username
  #end
  
  attr_accessor :living_city_base_id, :born_city_base_id#, :user_photo_id
  #invites_count


  def fullname
    "#{first_name} #{last_name}"
  end
  def username_at
    "@#{username}"
  end
  
  def website_dots
    (!website or website.length <= 20) ? website : "#{website[0..20]}..."
  end

  
  
  has_many :posts,      :dependent => :destroy
  has_many :likes,      :dependent => :destroy
  has_many :invites,    :dependent => :destroy

  belongs_to :born_city,  :class_name => "City"
  belongs_to :living_city, :class_name => "City"
  
  has_many :post_followers,  :dependent => :destroy
  has_many :post_user_news,  :dependent => :destroy



  

  def likes?(post_id)
    Like.likes?(self.id, post_id)
  end
  
  class << self
    #HELPER
    def create_sample
      s = MyF.chars
      a = new :username => s,
              :email    => "#{s}@executter.com",
              :password => s,
              :first_name    => "Nome",
              :last_name    => s
      a.register
      a
    end

    #CUSTOM METHODS
    def find_rescue(id)
      find(id) rescue nil
    end
    def findi(param_id)
      where(:id=>param_id).first
    end
    def findu(param_username)
      where(:username => param_username.downcase.delete("@")).first
    end
    def finde(param_email)
      where(:email => param_email.downcase).first
    end
    
    def is_username_at?(text)
      text[0]=='@' and is_username?(text)
    end
    
    def is_username?(text)
      text[1..-1] == text[USERNAME_REGEX]
    end
    def sex_options
      ['Masculino','Feminino']
    end
  end
    



  #EVENTS

  before_create do
    self.cached_photo_url = UserPhoto.new.image.url
  end

  after_create do
    recount_relations
  end
  
  
  alias :u_ :username_at
  alias :fn_ :fullname
  def p_
    self.attributes['cached_photo_url'] #|| photo.image.url(:thumb)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  sub_layout 'triple'
  
  before_filter :fill_user
  before_filter :must_login, :only => [:relate_panel, :relate]

  helper_method :user_me?,
                :profile_user

  def index
    @users = User.select([:id, :username, :first_name, :last_name, :user_photo_id]).limit(7).order('id DESC')
    render :layout=>false
  end

  def show
    return redirect_to :root unless @user
    unless current_user
      cookies[:interesting_user_ids] ||= ""
      cookies[:interesting_user_ids] += "#{@user.id},"
    end
    #@isme = @user.id == current_user_id
  end

  def ajax_relate_panel
    return render :nothing=>true if !cu || !@user
    render :layout=>false
  end

  def ajax_relate
    current_user.relate(@user, params[:relation_type])
    current_user.recount_relations
    @user.recount_relations
    #render :js=>"alert('server saved your #{option} :)')"
  end
  

  def likes
    @likes = Like.all
    render "/likes/index", :layout=>false
  end

  helper_method :user_cache_key
  
  before_filter :post_fill_hashes_from_profile,
                :only =>  [:ajax_posts_all,
                           :ajax_posts_status,
                           :ajax_posts_image
                           ]
                                             
  def ajax_posts_all
  end

  def ajax_posts_status
  end

  def ajax_posts_image
  end

  def ajax_relations_following
    @users = @user.followings_users.order('users.updated_at DESC').limit(25)
    render 'user', :layout=>false
  end
  def ajax_relations_follower
    @users = @user.followers_users.order('users.updated_at DESC').limit(25)
    render 'user', :layout=>false
  end
  def ajax_relations_friend
    @users = @user.friends_users.order('users.updated_at DESC').limit(25)
    render 'user', :layout=>false
  end

  def ajax_relations_sidebar_friend
    @users = @user.friends_users.order('users.updated_at DESC').limit(25)
    render 'user_sidebar', :layout=>false
  end

  caches_action :ajax_suggestions_sidebar, :expires_in=>5.minutes

  def ajax_suggestions_sidebar
    @width = 64
    @users = User.order('id DESC').limit(15)
    render 'user_sidebar', :layout=>false
  end

  
  protected

  def post_fill_hashes_from_profile
    @posts = Post.from_profile(@user, get_post_options) #unless fragment_exist? user_cache_key
    render('posts', :layout=>false)
  end
  
  def user_cache_key
    [@user.cache_key, action_name].join('/')
  end

  def user_me?
    current_user.try(:id) == @user.try(:id)
  end
  
  def fill_user
    if params[:user_id]||params[:id]
      @user = current_user if (current_user && current_user.id == params[:user_id]||params[:id])
      @user ||= User.find(params[:user_id]||params[:id])
    elsif params[:username]
      @user = current_user if (current_user && current_user.username.downcase == params[:username].downcase)
      @user ||= User.findu(params[:username])
    elsif current_user
      @user = current_user
    end
  end

  def profile_user
    @profile_user ||= fill_user
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def current_user_is_not_user
    !user_me?
  end
  
  def user_post_tabs_item(text, number, url, css_class)
    css_class = "icon-color #{css_class}"
    content = raw "#{text} #{content_tag :span, '', :class=>css_class} #{content_tag :strong, number}"
    content_tag :li, link_to(content, url)
  end

  def my_image_tag(url, o={:dimensions=>nil})
    o[:width], o[:height] = o[:dimensions], o[:dimensions] if o[:dimensions]
    image_tag url, o
  end

end

app/views/users/_col2.html.erb
<%= render '/cities/city_col2' %>
<%= render '/sponsor_col2' %>

app/views/users/_col3.html.erb
<%= background_image @user if @user %>
<% content_for :jsload do %>

  $("#user-post-tabs").tabs().show().removeClass('ui-widget-content').find("*").removeClass("ui-widget-header ui-corner-all ui-corner-top");
  $('#col3 #tabs-holder').html($("#user-post-tabs ul"));

<% end %>
  <div class="in">

  
<% if false %>
    <div class="title no-link-decoration">
      <span class="icon-color action-repo"></span>
      <%= link_to T.t('page.user.sidebar.email_verified').capitalize, profile_path(@user.username) %>
      <div class="clear">
      </div>
    </div>
<% end %>
    
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.user').capitalize)} #{link_to_username_mention @user.username}") %>
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.bio').capitalize)} #{@user.bio}") %>
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.web').capitalize)} #{link_to @user.website_dots, @user.website, :target=>'_blank'}") %>

  </div>

<% if false %>

  <table class="in no-link-decoration">
    <tr>
      <% a = raw("#{content_tag :strong, @user.rch[:followings]} #{content_tag :span, T.t('page.user.sidebar.columns.followings').downcase}") %>
      <td><%= link_to a, username_followings_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}") %>
      <td><%= link_to a, username_followers_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}") %>
      <td><%= link_to a, username_friends_url(@user.username) %></td>
    </tr>
  </table>
  
<% end %>




  <div class="clear">
  </div>

  <div id="tabs-holder" class="in-v">
  </div>
  
  <div class="clear">
  </div>


  <div class="in">
    
    <% if false %>
    <div class="clear line">
    </div>
    <div class="users">
      <div class="user">
        <%= link_to raw('<img width="48" height="48" src="http://images.wikia.com/deadliestfiction/images/4/47/Dexter_Morgan.jpg"/>'), profile_path(@user.username), :class=>'photo' %>
        <span>Está num relacionamento sério com </span>
        <%= link_to @user.fullname, profile_path(@user.username), :class=>'strong' %>
      </div>
    </div>
    <% end %>

    <div class="clear line">
    </div>
  
    <%= link_to "Amigos de @#{@user.username}", '/', :class=>"list-title strong" %>
    <div  id="sidebar_user_list"
          class="users"
          data-ajaxload-event="load"
          data-ajaxload-url="<%= user_ajax_relations_sidebar_friend_url(@user) %>"
          data-ajaxload-target="#sidebar_user_list"
          >
    </div>
    
    <div class="clear line">
    </div>
    
  </div>

app/views/users/_sidebar.html.erb
<%= background_image @user if @user %>
<% content_for :jsload do %>

  $("#user-post-tabs").tabs().show().removeClass('ui-widget-content').find("*").removeClass("ui-widget-header ui-corner-all ui-corner-top");
  $('.sidebar #tabs-holder').html($("#user-post-tabs ul"));

<% end %>
  <div class="in">

  
<% if false %>
    <div class="title no-link-decoration">
      <span class="icon-color action-repo"></span>
      <%= link_to T.t('page.user.sidebar.email_verified').capitalize, profile_path(@user.username) %>
      <div class="clear">
      </div>
    </div>
<% end %>
    
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.user').capitalize)} #{link_to_username_mention @user.username}") %>
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.bio').capitalize)} #{@user.bio}") %>
    <%= content_tag :p,
      raw("#{content_tag(:strong, T.t('page.user.sidebar.web').capitalize)} #{link_to @user.website_dots, @user.website, :target=>'_blank'}") %>

  </div>

<% if false %>

  <table class="in no-link-decoration">
    <tr>
      <% a = raw("#{content_tag :strong, @user.rch[:followings]} #{content_tag :span, T.t('page.user.sidebar.columns.followings').downcase}") %>
      <td><%= link_to a, username_followings_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}") %>
      <td><%= link_to a, username_followers_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}") %>
      <td><%= link_to a, username_friends_url(@user.username) %></td>
    </tr>
  </table>
  
<% end %>




  <div class="clear">
  </div>

  <div id="tabs-holder" class="in-v">
  </div>
  
  <div class="clear">
  </div>


  <div class="in">
    
    <% if false %>
    <div class="clear line">
    </div>
    <div class="users">
      <div class="user">
        <%= link_to raw('<img width="48" height="48" src="http://images.wikia.com/deadliestfiction/images/4/47/Dexter_Morgan.jpg"/>'), profile_path(@user.username), :class=>'photo' %>
        <span>Está num relacionamento sério com </span>
        <%= link_to @user.fullname, profile_path(@user.username), :class=>'strong' %>
      </div>
    </div>
    <% end %>

    <div class="clear line">
    </div>
  
    <%= link_to "Amigos de @#{@user.username}", '/', :class=>"list-title strong" %>
    <div  id="sidebar_user_list"
          class="users"
          data-ajaxload-event="load"
          data-ajaxload-url="<%= user_ajax_relations_sidebar_friend_url(@user) %>"
          data-ajaxload-target="#sidebar_user_list"
          >
    </div>
    
    <div class="clear line">
    </div>
    
  </div>

app/views/users/ajax_relate.js.erb
var t = $('.relate_panel');
var url = t.data('ajaxload-url');
t.load(url);

app/views/users/ajax_relate_panel.html.erb
<% cache [:ajax_relate_panel, current_user.id, @user.id, current_user.is_following?(@user)] do %>
<script type="text/javascript">
  $('.jqbutton').button().removeClass('ui-corner-all');
</script>
<% if current_user.is_following? @user %>

  <%= link_to "- UNFOLLOW", user_ajax_relate_path(@user, :relation_type=>:unfollow), :class=>'jqbutton do_it', :remote=>true, :method=>:put %>
  <strong>is following</strong>
  
<% else %>

  <%= link_to "+ FOLLOW",   user_ajax_relate_path(@user, :relation_type=>:follow),  :class=>'jqbutton do_it', :remote=>true, :method=>:put %>
  
<% end %>
<% end %>

app/views/users/index.html.erb
<% cache [:users, :recent, :photo_ids, @users.map(&:user_photo_id).join('-')] do %>
<script>registerContextMenu();</script>
  <% @users.each do |user| %>
    <div class="user">
      <%= link_to image_tag(user.p_, :width=>48, :height=>48), profile_path(user.username), :class=>'photo' %>
      <%=  %>
      <%= link_to user.fullname, profile_path(user.username), :class=>'strong' %>
      <br/>
      <%= link_to_username_mention user.username %>
      <div class="clear">
      </div>
    </div>
  <% end %>
  <%# if @users.last %>
  <% if false %>
  <% more_url = users_path(:before=>@users.last.id) %>
  <%= content_tag :li, link_to("MORE", "#", :class=>'more', :'data-url'=>more_url, :style=>'background-image:none') %>
  <% end %>
<% end %>

app/views/users/likes.html.erb
<h1>Listing likes</h1>

<table>
  <tr>
    <th>Post</th>
    <th>User</th>
  </tr>

<% @likes.each do |like| %>
  <tr>
    <td><%= like.post.id %></td>
    <td><%= link_to like.user.username_at, profile_path(like.user.username) %></td>
  </tr>
<% end %>
</table>

app/views/users/list.html.erb
<h1>Users#lislist</h1>
<p>Find me in app/views/users/lislist.html.erb</p>

app/views/users/posts.html.erb
<%# cache user_cache_key do %>
<%= render '/posts/index' %>
<%# end %>

app/views/users/show.html.erb
<%# cache user_cache_key do %>
<% content_for :jsload do %>
	functions.profile.ajax.append_behaviour();
  functions.posts.ajax.append_behaviour();
  functions.posts.more.append_behaviour();
<% end %>

<div class="card in">

  <%= my_image_tag @user.p_, :dimensions=>128, :id=>:photo %>
  
  <div class="about">
  
    <%= content_tag :h1, @user.fullname %>
    
    <% if current_user && current_user!=@user %>
    <div id="relatepanel" class="relate_panel"
                          data-ajaxload-event="load"
                          data-ajaxload-url="<%= user_ajax_relate_panel_url(@user) %>"
                          data-ajaxload-nocache="true"
                          data-ajaxload-target="#relatepanel">
    </div>
    <% end %>
    
    <p>
      <%= content_tag :span, '', :class=>'icon-color profile-birth-date' %>
      <%= content_tag :span, T.t('page.user.show.profile.birth_date', :date => l(@user.born_at, :format=>:long)) %>
      
      <% if false %>
      <%= content_tag :span, '', :class=>'icon-color profile-birth-place' %>
      <%= content_tag :span, T.t('page.user.show.profile.birth_city') %>
      <%= link_to @user.fullname, profile_path(@user.username) %>
      
      <%= content_tag :span, '', :class=>'icon-color profile-current-place' %>
      <%= content_tag :span, T.t('page.user.show.profile.current_city') %>
      <%= link_to @user.fullname, profile_path(@user.username) %>



      
        <%= content_tag :span, '', :class=>'icon-color profile-relationship' %>
        <%= content_tag :span, "Está em um relacionamento sério com" %>
        <%= link_to @user.fullname, profile_path(@user.username) %>
        
        <%= content_tag :span, '', :class=>'icon-color profile-language' %>
        <%= content_tag :span, "Fala #{@user.username_at}" %>
      <% end %>
    </p>
    
  </div>
  <div style="clear:both">
  </div>
</div>

<div id="user-post-tabs" style="display:none">
  <ul>
    <%= user_post_tabs_item T.t('page.user.show.post_tabs.all'),
                            @user.pch[:all],
                            user_ajax_posts_all_url(@user),    
                            'post-text' %>
    <%= user_post_tabs_item T.t('page.user.show.post_tabs.image'),
                            '',
                            user_ajax_posts_image_url(@user),    
                            'post-text' %>
                            
    <%= user_post_tabs_item @user.u_,
                            @user.pch[:mentions],
                            ajax_search_posts_url(:search=>@user.u_),
                            'post-file' %>
    <%= user_post_tabs_item @user.living_city.l_,
                            '',
                            ajax_search_posts_url(:search=>@user.living_city.l_),
                            'post-file' if @user.living_city %>
                            
    <%= user_post_tabs_item T.t('page.user.sidebar.columns.followings'),
                            @user.rch[:followings],
                            user_ajax_relations_following_url(@user),
                            'post-follow' %>
    <%= user_post_tabs_item T.t('page.user.sidebar.columns.followers'),
                            @user.rch[:followers],
                            user_ajax_relations_follower_url(@user), 
                            'post-follow' %>
    <%= user_post_tabs_item T.t('page.user.sidebar.columns.friends'),
                            @user.rch[:friends],
                            user_ajax_relations_friend_url(@user), 
                            'post-follow' %>
  </ul>
</div>
<%# end %>

app/views/users/user.html.erb
<% cache [:users, @user.id, controller.action_name, :photo_ids, @users.map(&:user_photo_id).join('-')] do %>
<% @users.each do |user| %>

<div data-user-id="<%= user.id %>" class="post">
  <div class="post-left">
    <%= my_image_tag user.p_, :dimensions=>64 %>
  </div>
  <div class="post-right">
    <div class="who">
      <%= link_to user.fullname, profile_path(user.username), :class=>'fullname' %>
      <%= link_to_username_mention user.username %>
    </div>
    <div class="text">
      <%= content_tag :span, '', :class=>'icon-color profile-birth-date' %>
      <%#= content_tag :span, T.t('page.user.show.profile.birth_date', :date => l(user.born_at, :format=>:long)) %>
    </div>

    <% if false %>
    
    <div class="actions">
      <%= post_actions_link l(post.created_at, :format => :short),
                            url_for(post),
                            'source-site',
                            :class=>'time', :'data-time'=>post.created_at.to_i %>
      <% if current_user %>
      <%= post_actions_link T.t('page.post.actions.like').capitalize,
                            post_like_path(post),
                            'action-like',
                            :remote=>true, :'data-method'=>:post, :class=>'like_it' %>
                            <%# and !current_user.likes?(post.id) %>
      <%= post_actions_link T.t('page.post.actions.repost').capitalize,
                            '#',
                            'action-repost',
                            :class=>'toggle_comment' if can_comment?(post) %>
      <%= post_actions_link T.t('page.post.actions.comment').capitalize,
                            '#',
                            'action-comment',
                            :class=>'toggle_comment' if can_comment?(post) %>
      <%= post_actions_link T.t('page.post.actions.trash').capitalize,
                            post,
                            'action-delete',
                            :class=>'delete-post',
                            :remote=>true,
                            :confirm => T.t('page.post.actions.trash_confirm').capitalize,
                            :method => :delete if post.user_id == current_user.id %>
      <% end %>
    </div>
    
    <% end %>
    
    
  </div>
  <div class="clear">
  </div>
</div>

<% end %>
<% end %>

app/views/users/user_sidebar.html.erb
<% cache [:users_sidebar, @user.id, controller.action_name, :photo_ids, @users.map(&:user_photo_id).join('-')] do %>
  <% @users.each do |user| %>
    <div class="user">
      <%= link_to my_image_tag(user.p_, :dimensions=>(@width || 48)), profile_path(user.username), :class=>'photo' %>
      <%=  %>
      <%= link_to user.fullname, profile_path(user.username), :class=>'strong' %>
      <br/>
      <%= link_to_username_mention user.username %>
      <div class="clear">
      </div>
    </div>
  <% end %>
<% end %>