config/routes.rb
Ex2::Application.routes.draw do

  get 'n' => "site#test"

  get "w/:text" => "google_search#search"

  get 'm' => 'mobile#index_posts', :as=>:mobile_root
  scope 'm', :as=>'mobile' do
    get "mentions"  => 'mobile#index_mentions'
    get 'posts'     => 'mobile#index_posts'
    post 'new_post' => 'mobile#index_new_post'
    get  "login" => 'mobile#login'
    post "login" => 'mobile#post_login'
    get "u/:username" => 'mobile#user', :as=>:user
    get "p/:id"            => 'mobile#post', :as=>:post
    post 'p/comment_create' => 'mobile#post_comment_create', :as=>:post_comment_create
    get "c/:label"  => 'mobile#city'
  end

  get 'c/:label' => 'cities#show', :as=>:city_label
  resources :cities, :only=>[:show] do
    collection do
      get 'base_search'
    end
  end

  scope 'a' do
    resources :smiles
    resources :user_agents, :only=>:index
    get 'user_sessions' => "user_sessions#index", :as=>'xxx'
    resources :translations, :path=>'t', :only=>[:index, :edit, :update] do
      collection do
        put   '' => 'translations#edit_multiple'
        post  '' => 'translations#update_multiple'
      end
    end
  end

  get 's/who_we_are' => 'site#who_we_are', :as => :s_who
  get 's/suggest' => 'suggestions#new', :as => :s_suggest
  

  resources :suggestions, :except => [:edit, :update]
  resources :user_sessions, :except => [:index, :edit, :update]
  
  get "u/out"    => "user_sessions#destroy",         :as => :out
  get "u/in"     => "user_sessions#new",             :as => :in
  get "u/new"    => redirect("r/new")
  
  get "u/send_password/:base64_key" => "user_sessions#send_password", :as =>:send_password
  get "u/new_password/:username/:token" => "user_sessions#new_password", :as =>:new_password
  post "u/create_password" => "user_sessions#create_password", :as =>:create_password

  get   "r/new"       => "registration#new"
  get   "r/new"       => "registration#new",          :as => :new
  post  "r/new"       => "registration#new_post"
  get   "r/captcha"   => "registration#captcha"
  post  "r/captcha"   => "registration#captcha_post"
  
  get "r/after_register"           => "registration#after_register"
=begin
  get "registration/new_by_profile"
  get "registration/new_by_invitation"
  get "registration/new_by_profile_post"
  get "registration/new_by_invitation_post"
  get "registration/confirm_email"
  get "registration/new_password"
  get "registration/new_password_post"

=end
  get  "e/basic"    => "edit#basic"
  put  "e/basic"    => "edit#basic_put"
  get  "e/cities"   => "edit#cities"
  put  "e/cities"   => "edit#cities_put"
  get  "e/username" => "edit#username"
  put  "e/username" => "edit#username_put"
  get  "e/email"    => "edit#email"
  put  "e/email"    => "edit#email_put"
  get  "e/password" => "edit#password"
  put  "e/password" => "edit#password_put"
  
  get  "e/photo" => "edit#photo"
  post "e/photo" => "edit#photo_post"
  
  get  "e/theme" => "edit#theme"
  post "e/theme" => "edit#theme_post"
=begin
  constraints :subdomain => "m" do
    get "s(/:text)"                 => "site#mobile_search"
    get "s/posts/:post_type/:text"  => "site#mobile_posts"
    root :to                        => "home#mobile_index"
  end
=end
  root :to => "home#index"

=begin
  get "search/paginated"
  get "search/async_holder"
  get "search/async_ajax"
=end

  get "s(/:text)" => "search#async", :as => :s
  get "s/posts/:post_type/:text" => "search#posts", :as => :search_posts
  get "z(/:text)" => "search#paginated"
  get "h/posts_followings_all_latest" => "home#posts_followings_all_latest"
  get "h/posts_followings_all"    => "home#posts_followings_all"
  get "h/posts_followings_status" => "home#posts_followings_status",  :filter => Post::CATEGORY_STATUS
  get "h/posts_followings_image"  => "home#posts_followings_image",   :filter => Post::CATEGORY_IMAGE
  get "h/posts_followings_audio"  => "home#posts_followings_audio",   :filter => Post::CATEGORY_AUDIO
  get "h/posts_followings_other"  => "home#posts_followings_other",   :filter => Post::CATEGORY_OTHER
  get "h/posts_followers"         => "home#posts_followers"
  get 'h/ajax_notifications'           => "home#ajax_notifications"
  get 'h/ajax_news_button'        => "home#ajax_news_button"
  post 'h/invite'           => "home#invite"
  post 'h/mark_notifications_as_read'           => "home#mark_notifications_as_read"
  get 'h/ajax_suggestions_sidebar'  => 'users#ajax_suggestions_sidebar', :as=> :user_ajax_suggestions_sidebar
  

  resources :posts, :path => "p", :only => [:show, :destroy] do
    get "ajax_likes"
    post "like"
    get "ajax_comments"
    collection do
      get "generate_notifications"
      post "create_status"
      post "create_image"
      post "create_comment"
      get "ajax_search"
    end
  end
=begin
  devise_for :users do
    get "/u/out" => "devise/sessions#destroy",  :as => :out
    get "/u/new" => "devise/registrations#new", :as => :new
    get "/u/in"  => "devise/sessions#new",      :as => :in
  end
=end
  
  resources :users, :path => "u" do#, :only =>[:show, :index] do #, :index, :update do
    get :ajax_posts_all
    get :ajax_posts_status,  :filter => :status
    get :ajax_posts_image,   :filter => :image

    get :ajax_relations_following,  :filter => :following
    get :ajax_relations_follower,   :filter => :follower
    get :ajax_relations_friend,     :filter => :friend
    
    get :ajax_relations_sidebar_friend,     :filter => :friend
    
    get :likes
    get :ajax_relate_panel
    put :ajax_relate
  end
  get ":username" => "users#show", :as => "profile", :constraints => { :username => User::USERNAME_REGEX }
  scope ":username", :constraints => { :username => User::USERNAME_REGEX } do
    get 'followings'  => "relations#followings",  :as => :username_followings
    get 'followers'   => "relations#followers",   :as => :username_followers
    get 'friends'     => "relations#friends",     :as => :username_friends
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  sub_layout 'triple'

  before_filter :must_login
  #authentication_token as a cache key for home controller

  before_filter do
    @user = cu
  end

  def mobile_index
    @posts = Post.from_relation(current_user, :followings, get_post_options)
  end


  def invite
    params[:emails].downcase.gsub(/,|;/,' ').split(' ').each do |email|
      if u = User.finde(email)
        current_user.relate(u, :follow)
      else
        current_user.invites.create(:email_to => email)
      end
    end
    current_user.recount_relations
    redirect_to :root
  end


  def index
  end


  def forms
    render :layout=>false
  end

  def ajax_notifications
    check_user_session
    @pun_list_unread_count = cu.post_user_news.where(:is_read => false).count
    pun_list = cu.post_user_news.order("id DESC")
    #@pun_list = pun_list.limit(6)
    @pun_grouping = cu.post_user_news.where('post_id IS NOT NULL').select('post_id, reason_why, reason_trigger, max(user_id_from) as user_id_from, max(created_at) as created_at, count(*)').group('post_id, reason_why, reason_trigger').limit(6).order('created_at DESC')
    @users_from = User.select([:id, :username, :user_theme_id, :cached_photo_url, :first_name, :last_name])
                      .find(@pun_grouping.map(&:user_id_from))
    render :layout=>false
  end

  def ajax_news_button
    return render :nothing => true unless cu.last_read_post_id
    @count = Post.from_relation_count_unread(cu, :followings)
    render :layout=>false
  end

  def mark_notifications_as_read
    PUN.update_all({:is_read => true}, {:user_id => current_user.id})
    render :nothing=>true
  end

  # partial html via ajax

  def posts_followings_all_latest
    @posts = Post.from_relation(cu_ro, :followings, {:after=>cu_ro.last_read_post_id})
    @no_more = true
    User.update(cu_ro.id, :last_read_post_id => @posts.first.id) if @posts.first
    #expires_cache many
    render '/posts/index', :layout=>false
  end
  
  def posts_followings_all
    @posts = Post.from_relation(cu_ro, :followings, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_followings_status
    @posts = Post.from_relation(cu_ro, :followings, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_followings_image
    @posts = Post.from_relation(cu_ro, :followings, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_followings_audio
    @posts = Post.from_relation(cu_ro, :followings, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_followings_other
    @posts = Post.from_relation(cu_ro, :followings, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_followers
    @posts = Post.from_relation(cu_ro, :followers, get_post_options)
    render '/posts/index', :layout=>false
  end
  def posts_mention
    @posts = Post.from_search(cu_ro.u_, get_post_options)
    render '/posts/index', :layout=>false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_col2.html.erb
<%= render '/cities/city_col2' %>
<%= render '/sponsor_col2' %>

<div class="users">

  <div class="clear line">
  </div>
  
  <h2>Suggestions</h2>
  
  <div  id="col2_user_list"
        class="users"
        data-ajaxload-event="load"
        data-ajaxload-url="<%= user_ajax_suggestions_sidebar_url %>"
        data-ajaxload-target="#col2_user_list"
        >
  </div>
  
  <div class="clear line">
  </div>
</div>

app/views/home/_col3.html.erb
<%= background_image current_user if current_user %>
<% if current_user %>
  <div class="users">
    <div class="user">
      <%= link_to my_image_tag(@user.p_, :dimensions=>32), :e_photo, :class=>'photo' %>
      <%= link_to @user.fullname, profile_path(@user.username), :class=>'strong' %>
      <br/>
      <%= link_to T.t('page.home.sidebar.edit_profile').downcase, :e_basic %>
    </div>
  </div>
  <div class="clear">
  </div>
  
  <div class="users">
  
    <div class="clear line">
    </div>
    
    <%= link_to "Meus Amigos", '/', :class=>"list-title strong" %>
    <div  id="col3_user_list"
          class="users"
          data-ajaxload-event="load"
          data-ajaxload-url="<%= user_ajax_relations_sidebar_friend_url(cu_ro) %>"
          data-ajaxload-target="#col3_user_list"
          >
    </div>
    
    <div class="clear line">
    </div>
  </div>
<% end %>


<% if false %>
  <div class="in" style="margin-top:25px;">
    <%= form_tag :h_invite do %>
      <h2>email, email, email</h2>
      <%= text_area_tag :emails %>
      <%= submit_tag "invite them", :class=>"ui-button", :style=>"width:100%" %>
    <% end %>
  </div>
  <div class="clear">
  </div>

  <table class="no-link-decoration">
    <tr>
      <% a = raw("#{content_tag :strong, @user.rch[:followings]} #{content_tag :span, T.t('page.user.sidebar.columns.followings').downcase}") %>
      <td><%= link_to a, username_followings_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}") %>
      <td><%= link_to a, username_followers_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}") %>
      <td><%= link_to a, username_friends_url(@user.username) %></td>
    </tr>
  </table>



  <ul class="ex2tabs table no-link-decoration">
    <li></li>
    <li><%= link_to raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}"), username_followers_url(@user.username) %></li>
    <li><%= link_to raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}"), username_friends_url(@user.username) %></li>
  </ul>

  <div class="clear">
  </div>
<% end %>

app/views/home/_forms.html.erb
<%content_for :jsload do %>
  functions.home.ajax.append_behaviour();
<% end %>

<div id="home-form-tabs" class="in">
	<ul>
		<li class="disabled">
      <span class="ui-icon icon-color action-repost"></span>
      <%= T.t('page.home.form_tabs.share').capitalize %>:
		  </li>
		<li><a href="#tabs-1">
      <span class="ui-icon icon-color post-text selected"></span>
		  <%= T.t('page.home.form_tabs.status').capitalize %>
		  </a></li>
		<li><a href="#tabs-2">
      <span class="ui-icon icon-color post-image"></span>
		  <%= T.t('page.home.form_tabs.image').capitalize %>
		</a></li>
	</ul>
	<div id="tabs-1">

<%= form_tag create_status_posts_url, :remote=>true, :class=>'new_topic', :id=>'create_status' do %>
  <div class="field">
    <%= text_area_tag :body, @mention, :rows=>3, :maxlength=>196 %>
    <span class="chars">196</span>
    <%= submit_tag "Executter" %>
    <div class="clear">
    </div>
  </div>
  
<% end %>
		
	</div>
	<div id="tabs-2">


<%= form_tag create_image_posts_url, :multipart=>true, :class=>'new_topic', :id=>'create_image' do %>
  <div class="field">
    <%= text_area_tag :body, '', :rows=>3, :maxlength=>196 %>
    <span class="chars">196</span>
    <%= submit_tag "Executter" %>
    <div class="clear">
    </div>
  </div>
  <strong><%= T.t('page.home.form_tabs.image').upcase %>: </strong>
  
  <%= file_field_tag :image %>
<% end %>

		
	</div>
</div>

app/views/home/_sidebar.html.erb
<%= background_image current_user if current_user %>
<% if current_user %>
  <div class="users in">
    <div class="user">
      <%= link_to my_image_tag(@user.p_, :dimensions=>32), :e_photo, :class=>'photo' %>
      <%= link_to @user.fullname, profile_path(@user.username), :class=>'strong' %>
      <br/>
      <%= link_to T.t('page.home.sidebar.edit_profile').downcase, :e_basic %>
    </div>
  </div>
  <div class="clear">
  </div>
<% if false %>
  <div class="in" style="margin-top:25px;">
    <%= form_tag :h_invite do %>
      <h2>email, email, email</h2>
      <%= text_area_tag :emails %>
      <%= submit_tag "invite them", :class=>"ui-button", :style=>"width:100%" %>
    <% end %>
  </div>
  <div class="clear">
  </div>

  <table class="in no-link-decoration">
    <tr>
      <% a = raw("#{content_tag :strong, @user.rch[:followings]} #{content_tag :span, T.t('page.user.sidebar.columns.followings').downcase}") %>
      <td><%= link_to a, username_followings_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}") %>
      <td><%= link_to a, username_followers_url(@user.username) %></td>

      <% a = raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}") %>
      <td><%= link_to a, username_friends_url(@user.username) %></td>
    </tr>
  </table>



  <ul class="in ex2tabs table no-link-decoration">
    <li></li>
    <li><%= link_to raw("#{content_tag :strong, @user.rch[:followers]} #{content_tag :span, T.t('page.user.sidebar.columns.followers').downcase}"), username_followers_url(@user.username) %></li>
    <li><%= link_to raw("#{content_tag :strong, @user.rch[:friends]} #{content_tag :span, T.t('page.user.sidebar.columns.friends').downcase}"), username_friends_url(@user.username) %></li>
  </ul>

<% end %>
  <div class="clear">
  </div>
  
  <div class="in">
    <%= link_to cu.city.l_, city_label_path(cu.city.label) if cu.city %>
  </div>
  
  <div class="clear">
  </div>
  
  <div class="users in">
  
    <div class="clear line">
    </div>
    

    <%= link_to "Meus Amigos", '/', :class=>"list-title strong" %>
    <div  id="sidebar_user_list"
          class="users"
          data-ajaxload-event="load"
          data-ajaxload-url="<%= user_ajax_relations_sidebar_friend_url(cu_ro) %>"
          data-ajaxload-target="#sidebar_user_list"
          >
    </div>
    
    <div class="clear line">
    </div>
  </div>
<% end %>

app/views/home/ajax_news_button.html.erb
<% count_str = @count >= 10 ? '10+' : @count %>
<% count_str = "#{pluralize @count, 'novidade'}" %>
<script type="text/javascript">
  <%= "$title1='#{count_str}';" unless @count.zero? %>
  make_button();
  setTimeout(load_post_news_button, NOTIFICATIONS_DELAY);
</script>
<%= link_to count_str, :root, :style=>'width:100%', :class=>'ui-button' unless @count.zero? %>

app/views/home/ajax_notifications.html.erb
<% simple_digest = Digest::MD5.hexdigest(@pun_grouping.map(&:created_at).to_s) %>
<% cache [:ajax_news, :unread, @pun_list_unread_count, :md5, simple_digest], :expires_in=>10.minutes do %>

<script type="text/javascript">
<% if @pun_list_unread_count > 0 %>
  $('#bell').html("<span><%= @pun_list_unread_count %></span>");
  $title2 = "NEW (<%= @pun_list_unread_count %>)";
<% end%>
  setTimeout(load_notifications, NOTIFICATIONS_DELAY);
</script>
<%= bitly %>

<% @pun_grouping.each do |pun| %>
  <% user_from = nil %>
  <% @users_from.each do |u| %>
    <% user_from = u if u.id == pun.user_id_from %>
  <% end %>
  
  <% pun_path_to = post_path(pun.post_id) %>
  <div class="anchor" href="<%= pun_path_to %>">
    <%= image_tag user_from.p_, :width=>45, :height=>45 %>
    <span>
      <strong>
        <%= user_from.fn_ %>
        <%= "and other #{pun.count} users" if pun.count.to_i > 1 %>
      </strong>
      <%= reason = T.t "notifications.simple.trigger_#{pun.reason_trigger}_why_#{pun.reason_why}" %>
      <br/>
      <%= post_actions_link l(pun.created_at, :format => :short),
                            pun_path_to,
                            'source-site',
                            :class=>'time', :'data-time'=>pun.created_at.to_i %>
    </span>
  </div>
<% end %>

<%# if @pun_list.size > 0 %>
<% if false %>

  <% @pun_list.each do |pun| %>
    <% user_from = User.kv_find(pun.user_id_from) %>
    <% pun_path_to = pun.post_id ? post_path(pun.post_id) : profile_path(user_from.username) %>
    <div class="anchor" href="<%= pun_path_to %>">
      <%= image_tag user_from.p_, :width=>45, :height=>45 %>
      <% reason = T.t "notifications.simple.trigger_#{pun.reason_trigger}_why_#{pun.reason_why}" %>
      <span>
      <%= raw "<strong>#{user_from.fn_}</strong> #{reason}" %>
      <br/>
      <%= post_actions_link l(pun.created_at, :format => :short),
                            pun_path_to,
                            'source-site',
                            :class=>'time', :'data-time'=>pun.created_at.to_i %>
      </span>
    </div>
  <% end %>
<% end %>

<% end %>

app/views/home/forms.html.erb
<script type="text/javascript">
  functions.home.ajax.append_behaviour();
  if (mention_username) {
    mention(mention_username);
    mention_username=false;
  }
  $("#home-form-tabs textarea:first").focus();
</script>

<div id="home-form-tabs" class="in" style="display:none">
	<ul>
		<li class="disabled">
      <span class="ui-icon icon-color action-repost"/>
      <%= T.t('page.home.form_tabs.share').capitalize %>:
		  </li>
		<li><a href="#tabs-1">
      <span class="ui-icon icon-color post-text selected"/>
		  <%= T.t('page.home.form_tabs.status').capitalize %>
		  </a></li>
		<li><a href="#tabs-2">
      <span class="ui-icon icon-color post-image"/>
		  <%= T.t('page.home.form_tabs.image').capitalize %>
		</a></li>
	</ul>
	<div id="tabs-1">

<%= form_tag create_status_posts_url, :multipart=>true, :class=>'new_topic' do %>
  <div class="field">
    <%= text_area_tag :body, params[:mention], :rows=>3, :maxlength=>196 %>
    <span class="chars">196</span>
    <%= submit_tag "Executter" %>
    <div class="clear">
    </div>
  </div>
  
<% end %>
		
	</div>
	<div id="tabs-2">


<%= form_tag create_image_posts_url, :multipart=>true, :class=>'new_topic' do %>
  <div class="field">
    <%= text_area_tag :body, '', :rows=>3, :maxlength=>196 %>
    <span class="chars">196</span>
    <%= submit_tag "Executter" %>
    <div class="clear">
    </div>
  </div>
  <strong><%= T.t('page.home.form_tabs.image').upcase %>: </strong>
  
  <%= file_field_tag :image %>
<% end %>

		
	</div>
</div>

app/views/home/index.html.erb
<% content_for :jsload do %>
  functions.posts.ajax.append_behaviour();
  functions.posts.more.append_behaviour();
  <%= "mention_username = ':mention';".gsub(':mention', params[:mention]) if params[:mention] %>
<% end %>

<% if cu_ro.admin? %>
  <div class="in">
  <%= request.user_agent %>
  </div>
<% end %>
  
  <%= render '/home/forms' %>

  <div id="home-news-holder">
  </div>

  <div id="home-post-tabs" style="display:none">
    <ul class="in-h">
      <%= li link_to T.t('page.home.post_tabs.home'),  h_posts_followings_all_url %>
      <%= li link_to T.t('page.home.post_tabs.image'), h_posts_followings_image_url %>
      
      <%= li link_to "@ #{@user.pch[:mentions]}",  ajax_search_posts_url(:search=>@user.u_) %>
      <%= li link_to @user.living_city.l_,         ajax_search_posts_url(:search=>@user.living_city.l_) if @user.living_city %>
      <% if false %>
      <li><%= link_to T.t('page.home.post_tabs.status'),        :h_posts_followings_status %></li>
      <li><%= link_to T.t('page.home.post_tabs.my_followers'),  :h_posts_followers %></li>
      <% end %>
    </ul>
  </div>

app/views/home/invite.html.erb
<%  %>

app/views/home/mobile_index.html.erb
<%= form_tag create_post_posts_url, :multipart=>true, :class=>'new_topic' do %>
  <div class="field">
    <%= text_area_tag :body, '', :rows=>3, :maxlength=>196 %>
    <span class="chars">196</span>
    <%= submit_tag "Executter" %>
    <div class="clear">
    </div>
  </div>
  
<% end %>

<%= render @posts %>