config/routes.rb
Ex2::Application.routes.draw do

  get 'n' => "site#test"

  get "w/:text" => "google_search#search"

  get 'm' => 'mobile#index_posts', :as=>:mobile_root
  scope 'm', :as=>'mobile' do
    get "mentions"  => 'mobile#index_mentions'
    get 'posts'     => 'mobile#index_posts'
    post 'new_post' => 'mobile#index_new_post'
    get  "login" => 'mobile#login'
    post "login" => 'mobile#post_login'
    get "u/:username" => 'mobile#user', :as=>:user
    get "p/:id"            => 'mobile#post', :as=>:post
    post 'p/comment_create' => 'mobile#post_comment_create', :as=>:post_comment_create
    get "c/:label"  => 'mobile#city'
  end

  get 'c/:label' => 'cities#show', :as=>:city_label
  resources :cities, :only=>[:show] do
    collection do
      get 'base_search'
    end
  end

  scope 'a' do
    resources :smiles
    resources :user_agents, :only=>:index
    get 'user_sessions' => "user_sessions#index", :as=>'xxx'
    resources :translations, :path=>'t', :only=>[:index, :edit, :update] do
      collection do
        put   '' => 'translations#edit_multiple'
        post  '' => 'translations#update_multiple'
      end
    end
  end

  get 's/who_we_are' => 'site#who_we_are', :as => :s_who
  get 's/suggest' => 'suggestions#new', :as => :s_suggest
  

  resources :suggestions, :except => [:edit, :update]
  resources :user_sessions, :except => [:index, :edit, :update]
  
  get "u/out"    => "user_sessions#destroy",         :as => :out
  get "u/in"     => "user_sessions#new",             :as => :in
  get "u/new"    => redirect("r/new")
  
  get "u/send_password/:base64_key" => "user_sessions#send_password", :as =>:send_password
  get "u/new_password/:username/:token" => "user_sessions#new_password", :as =>:new_password
  post "u/create_password" => "user_sessions#create_password", :as =>:create_password

  get   "r/new"       => "registration#new"
  get   "r/new"       => "registration#new",          :as => :new
  post  "r/new"       => "registration#new_post"
  get   "r/captcha"   => "registration#captcha"
  post  "r/captcha"   => "registration#captcha_post"
  
  get "r/after_register"           => "registration#after_register"
=begin
  get "registration/new_by_profile"
  get "registration/new_by_invitation"
  get "registration/new_by_profile_post"
  get "registration/new_by_invitation_post"
  get "registration/confirm_email"
  get "registration/new_password"
  get "registration/new_password_post"

=end
  get  "e/basic"    => "edit#basic"
  put  "e/basic"    => "edit#basic_put"
  get  "e/cities"   => "edit#cities"
  put  "e/cities"   => "edit#cities_put"
  get  "e/username" => "edit#username"
  put  "e/username" => "edit#username_put"
  get  "e/email"    => "edit#email"
  put  "e/email"    => "edit#email_put"
  get  "e/password" => "edit#password"
  put  "e/password" => "edit#password_put"
  
  get  "e/photo" => "edit#photo"
  post "e/photo" => "edit#photo_post"
  
  get  "e/theme" => "edit#theme"
  post "e/theme" => "edit#theme_post"
=begin
  constraints :subdomain => "m" do
    get "s(/:text)"                 => "site#mobile_search"
    get "s/posts/:post_type/:text"  => "site#mobile_posts"
    root :to                        => "home#mobile_index"
  end
=end
  root :to => "home#index"

=begin
  get "search/paginated"
  get "search/async_holder"
  get "search/async_ajax"
=end

  get "s(/:text)" => "search#async", :as => :s
  get "s/posts/:post_type/:text" => "search#posts", :as => :search_posts
  get "z(/:text)" => "search#paginated"
  get "h/posts_followings_all_latest" => "home#posts_followings_all_latest"
  get "h/posts_followings_all"    => "home#posts_followings_all"
  get "h/posts_followings_status" => "home#posts_followings_status",  :filter => Post::CATEGORY_STATUS
  get "h/posts_followings_image"  => "home#posts_followings_image",   :filter => Post::CATEGORY_IMAGE
  get "h/posts_followings_audio"  => "home#posts_followings_audio",   :filter => Post::CATEGORY_AUDIO
  get "h/posts_followings_other"  => "home#posts_followings_other",   :filter => Post::CATEGORY_OTHER
  get "h/posts_followers"         => "home#posts_followers"
  get 'h/ajax_notifications'           => "home#ajax_notifications"
  get 'h/ajax_news_button'        => "home#ajax_news_button"
  post 'h/invite'           => "home#invite"
  post 'h/mark_notifications_as_read'           => "home#mark_notifications_as_read"
  get 'h/ajax_suggestions_sidebar'  => 'users#ajax_suggestions_sidebar', :as=> :user_ajax_suggestions_sidebar
  

  resources :posts, :path => "p", :only => [:show, :destroy] do
    get "ajax_likes"
    post "like"
    get "ajax_comments"
    collection do
      get "generate_notifications"
      post "create_status"
      post "create_image"
      post "create_comment"
      get "ajax_search"
    end
  end
=begin
  devise_for :users do
    get "/u/out" => "devise/sessions#destroy",  :as => :out
    get "/u/new" => "devise/registrations#new", :as => :new
    get "/u/in"  => "devise/sessions#new",      :as => :in
  end
=end
  
  resources :users, :path => "u" do#, :only =>[:show, :index] do #, :index, :update do
    get :ajax_posts_all
    get :ajax_posts_status,  :filter => :status
    get :ajax_posts_image,   :filter => :image

    get :ajax_relations_following,  :filter => :following
    get :ajax_relations_follower,   :filter => :follower
    get :ajax_relations_friend,     :filter => :friend
    
    get :ajax_relations_sidebar_friend,     :filter => :friend
    
    get :likes
    get :ajax_relate_panel
    put :ajax_relate
  end
  get ":username" => "users#show", :as => "profile", :constraints => { :username => User::USERNAME_REGEX }
  scope ":username", :constraints => { :username => User::USERNAME_REGEX } do
    get 'followings'  => "relations#followings",  :as => :username_followings
    get 'followers'   => "relations#followers",   :as => :username_followers
    get 'friends'     => "relations#friends",     :as => :username_friends
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  sub_layout 'triple'

  before_filter :must_login, :except => [:show, :generate_notifications]
#  caches_action  :generate_notifications, :expires_in => 1.minutes

  # POST /posts/create_post_status
  def create_status
    current_user.posts.create  :remote_ip  => request.remote_ip,
                               :body       => params[:body],
                               :files_categories => Post::CATEGORY_STATUS
    render :text=>"after_post_create_status();"
  end

  # POST /posts/create_post_image
  def create_image
    current_user.posts.create do |post|
      post.remote_ip  = request.remote_ip
      post.body       = params[:body]
      if params[:image]
        post.image = params[:image]
        post.files_categories = Post::CATEGORY_IMAGE
      else
        post.files_categories = Post::CATEGORY_STATUS
      end
    end
    redirect_to :root
  end
  

  # POST /posts/create_comment
  def create_comment
    if post = Post.find(params[:post][:post_id]) rescue nil
      post ||= post.post
      comment = current_user.posts.create :remote_ip  => request.remote_ip,
                                          :body       => params[:post][:body],
                                          :post_id    => post.id,
                                          :files_categories => post.files_categories,
                                          :files_extensions => post.files_extensions
    end
    render :nothing=>true
  end

  # GET /posts/1
  def show
    post_id = params[:id].split('-').first
    redirect_to :root unless @post = Post.find(post_id)
    redirect_to @post.post if @post.post
    @user = @post.user
  end

  # GET /posts/1/ajax_comments
  def ajax_comments
    post = Post.find(params[:post_id])
    limit = params[:limit] || 50
    @comments = post.posts.size > 0 ? post.posts.order(:id) : []
    @users_hash = {}
    if @comments.size > 0
      users_id = @comments.map(&:user_id)
      users = User.select([:id, :username, :first_name, :last_name, :user_photo_id])
                  .where(:id=>users_id.uniq)
                  .limit(limit)
                  .includes(:user_photo)
      users.each { |u| @users_hash[u.id] = u }
    end
    render :layout => false
  end

  # GET /posts/ajax_posts_search
  def ajax_search
    string = params[:search].try(:downcase)
    options = {:before => params[:before]}
    @posts = Post.from_search(string, options)
    render('/posts/index', :layout=>false)
  end

  # POST /posts/1/like
  def like
    redirect_to :root unless @post = Post.find(params[:post_id])
    @post.like_it(current_user.id)
    render :nothing=>true
    #render :js=>"alert('servidor recebeu    thats the way!          Aham Aham...              I like it!')"
  end
  
  # GET /posts/1/ajax_likes
  def ajax_likes
    return render :nothing=>true unless @post = Post.find(params[:post_id])
    @likes_users = @post.likes_users.select([:username, :cached_photo_url])
    render :layout=>false
  end

  # DELETE /posts/1
  def destroy
    @post = Post.find(params[:id])
    @post.destroy if @post.user_id == cu_ro.id || @post.post.try(:user_id) == cu_ro.id
    render :nothing=>true
  end

  def generate_notifications
    #giving a little while to generate notifications helps because some of them will be deleted during this while
    Post.where(:generated_notifications=>false)
        .limit(30)
        .each &:assign_notifications
    Post.where(:generated_words=>false)
        .limit(30)
        .each &:create_words
    render :nothing => true
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def can_comment?(post)
    !post.repost? and current_user
  end

  def nice_time(time)
    #l(post.created_at, :format => :long)
    #l(post.created_at, :format => :short)
    time_ago_in_words time
  end

  def post_get_comments(post)
    limit = controller.controller_name=='post' ? 50 : 3
    post.post ? [post.post] : post.posts.limit(limit).order("ID desc").reverse
  end

  def page_post_show?
    controller.controller_name=='posts'
  end

  def post_actions_link(text, url, css_class, options={})
    css_class = "icon-color #{css_class}"
    
    content = raw "#{text} #{content_tag :span, '', :class=>css_class}"
    link_to content, url, options
  end

  def link_to_username(w, mention_helper=true)
    a = w.downcase[1..-1]
    return w unless b = a[User::USERNAME_REGEX]
    #random_id="mention-user-#{rand(99999999)}"
    #link_to("@#{username}", "/#{username}", :class=>:user, :id=>random_id)
    c = a.gsub(b,'')
    url = @mobile ? "/m/u/#{a}" : "/#{a}"
    d = link_to "@#{a}", url, {:class=>'username', :title=>"Ver Perfil de @#{a}"}
    "#{d}#{c}"
  end

  def link_to_username_mention(username)
    url = @mobile ? "/m/u/#{username}" : "/#{username}"
    link_to "@#{username}", url, {:class=>'username-mention', :title=>"Mencionar @#{username}"}
  end

  def link_to_search(w)
    a = w[1..-1]
    return w unless b = a[User::USERNAME_REGEX]
    c = a.gsub(b,'')
    #url = @mobile ? "/m/s/#{username}" : "/s/#{title}"
    url = "/s/#{a}"
    d = link_to "##{a}", url, :class=>:search
    "#{d}#{c}"
  end
  
  def link_to_city(w)
    a = w[1..-1]
    return w unless b = a[City::LABEL_REGEX]
    c = a.gsub(b,'')
    #url = @mobile ? "/m/c/#{label}" : "/c/#{label}"
    url = "/c/#{a}"
    d = link_to "$#{a}", url, :class=>:city
    "#{d}#{c}"
  end
  
  def link_to_google_search(w)
    a = w[1..-1]
    return w if a.blank?
    #"#{link_to_google_search(b)}#{c}"
    #url = @mobile ? "/m/c/#{text}" : "/c/#{text}"
    url = "/w/#{a}"
    link_to "!#{a}", url, :class=>:web
  end
  
=begin
w.starts_with?('www')
w: '@username...'
a: 'username...'
b: 'username'
c: '...'
d: '@username'
e: '/username'
=end
  def my_post_links(s)
    s = s.gsub("\r"," ")
    user_key = "@"
    group_key = "#"
    city_key = "$"
    google_search_key = "!"
    r = s.split(/\s/).collect do |w|
      if w[0,1]==user_key
        link_to_username(w)
      elsif w[0,1]==group_key
        link_to_search(w)
      elsif w[0,1]==city_key
        link_to_city(w)
      elsif w[0,1]==google_search_key
        link_to_google_search(w)
      elsif w[0..2] == 'www' || w[0..6]=='http://' || w[0..5]=='ftp://' || w[0..7]=='https://'
        w2 = "http://#{w}" if w[0..2] == 'www'
        link_to w, w2||w, :target=>'_blank'
      # elsif smile_url = Smile.all_as_hash[w]
      #   image_tag smile_url
      else
        h w
      end
    end
    raw r.join(" ")
  end
end

app/views/posts/_col2.html.erb
<%= render '/sponsor_col2' %>

app/views/posts/_col3.html.erb
<%= background_image @user if @user %>
    
<%= content_tag :p, raw("#{content_tag(:strong, "User")} #{@user.username}") %>
<%= content_tag :p, raw("#{content_tag(:strong, "Bio")} #{@user.bio}") %>
<%= content_tag :p, raw("#{content_tag(:strong, "Web")} #{link_to @user.website_dots, @user.website, :target=>'_blank'}") %>

app/views/posts/_comment.html.erb
<% user = User.kv_find(comment.user_id) %>
<div class="comment">
  <div class="comment-left">
    <%= link_to my_image_tag(user.p_, :dimensions=>32), profile_path(user.username) %>
  </div>
  <div class="comment-right">
    <div class="comment-text">
      <%= link_to user.fullname, profile_path(user.username), :class=>'comment-fullname' %>
      <%= my_post_links Post.kv_find_id(comment.id).body %>
    </div>
    <div class="comment-actions">
      <%= content_tag :span, "#{nice_time(comment.created_at)} via #{comment.origin}", :class=>'comment-time' %>
      <% if cu_ro %>
        <%= post_actions_link T.t('page.post.actions.like'),
                              post_like_path(comment),
                              'les',
                              :remote=>true, :'data-method'=>:post, :class=>'like_it' %>
        <%= post_actions_link T.t('page.post.actions.trash'),
                              comment,
                              'comme',
                              :class=>'delete-comment', :remote=>true, :confirm => 'Are you sure?', :method => :delete if [comment.user_id, comment.post.user_id].include? cu_ro.id %>
     <% end %>
    </div>
  </div>
  <div class="clear">
  </div>
</div>

app/views/posts/_index.html.erb
<%= render @posts %>

<% if @posts.length == Post::DEFAULT_LIMIT and !@no_more %>
<% more_url = url_for params.merge({:before=>@posts.last.id}) %>
<%= link_to "MORE", "#", :class=>'more ui-button', :'data-url'=>more_url %>
<% end %>

<script type="text/javascript">
make_button();
make_colorbox();
registerContextMenu();
</script>
<%= bitly %>

app/views/posts/_post.html.erb
<% user = User.kv_find(post.user_id) %>
<%# original_post = post.post || post %>

              <%#= raw "<span style='color:#fff;font-weight:bold;'>R</span>" if comment.repost? %>

<div
  data-post-id="<%= post.id %>"
  class="post<%= ' page-last' if @posts && @posts.last == post %>"
  data-comments-url="<%= post_ajax_comments_path(post, :limit=>(page_post_show? ? 50 : 3)) %>"
  data-comments-target="#post-<%= post.id %>-comments"
  >
  <div class="post-left">
    <%= link_to my_image_tag(user.p_, :dimensions=>64), profile_path(user.username) %>
  </div>
  <div class="post-right">
    <div class="who">
      <%= link_to user.fullname, profile_path(user.username), :class=>'fullname' %>
      <%= link_to_username_mention(user.username) %>
    </div>
    <div class="text">
      <%= my_post_links post.cached_body %>
    </div>

<%#  YOUTUBE IS EQUAL TO POST FILES   %>


<% youtube(post.cached_body).each do |iframe| %>

  <div class="line-files">
  </div>
  <%= raw iframe %>
  
  <div class="line-last">
  </div>
    
<% end %>

<%#  YOUTUBE IS EQUAL TO POST FILES   %>
    

<% if post.i_ %>
  <div class="line-files">
  </div>
  <%= link_to image_tag(post.i_), post.i_, :class=>'thumbnail', :rel=>'thumbnail' %>
  <div class="file-get">
    <%#= raw "#{content_tag :strong, pf.cod} #{T.t('page.post.file.views').capitalize}" %>
    <%= link_to T.t('page.post.file.download').downcase, post.i_, :target=>'_blank' %>
    <%#= link_to T.t('page.post.file.view_all').downcase, '/' %>
  </div>
  <div class="line-last">
  </div>
<% end %>



    <div class="actions" style="margin-bottom:5px">
      <%= post_actions_link "#{nice_time(post.created_at)} via #{post.origin}",
                            url_for(post),
                            'source-site',
                            :class=>'time', :'data-time'=>post.created_at.to_i %>
      <% if cu_ro %>
      <%= post_actions_link T.t('page.post.actions.like').capitalize,
                            post_like_path(post),
                            'action-like',
                            :remote=>true, :'data-method'=>:post, :class=>'like_it' %>
                            <%# and !cu_ro.likes?(post.id) %>
      <%= post_actions_link T.t('page.post.actions.comment').capitalize,
                            '#',
                            'action-comment',
                            :class=>'toggle_comment' if can_comment?(post) %>
      <%= post_actions_link 'x',
                            post,
                            'action-delete',
                            :class=>'delete-post',
                            :remote=>true,
                            :confirm => T.t('page.post.actions.trash_confirm').capitalize,
                            :method => :delete if post.user_id == cu_ro.id %>
      <% end %>
    </div>
    <% condition_1 = post.likes.size > 0 %>
    <% condition_2 = post.posts.size > 0 && !page_post_show? %>
    <% if condition_1 || condition_2 %>
    <div class="info_box">
      <% if condition_1 %>
      <div class="info">
        <%= content_tag :small, '', :class=>'icon-color action-like' %>
        <%= content_tag :p do %>
          <%= link_to "#{post.likes.size} #{T.t('page.post.details.user_s')}",
                      post_ajax_likes_path(post, :update=>"post-#{post.id}-likes", :format=>:js),
                      :remote=>true
                      %>
          <%= T.t('page.post.details.liked_this') %>
        <% end %>
      </div>
      <% end %>
      <% if condition_2 and false %>
      <div class="info">
        <%= content_tag :small, '', :class=>'icon-color action-repost' %>
        <% content_link = link_to "#{post.posts.size} #{T.t('page.post.details.repost_s')}", post %>
        <%= content_tag :p do %>
          <%= raw "#{T.t('page.post.details.received')} #{content_link}" %>
        <% end %>
      </div>
      <% end %>
      <% if condition_2 %>
      
      <div class="info">
        <%= content_tag :small, '', :class=>'icon-color action-comment' %>
        <% content_link = link_to T.t('page.post.details.show_all_x_comments', :count=>post.posts.size), post %>
        <%= content_tag :p do %>
          <a href="#" rel="post-comments-loader"
            data-url="<%= post_ajax_comments_path(post) %>"
            data-target="#post-<%= post.id %>-comments"
            >
            <%= T.t('page.post.details.show_all_x_comments', :count=>post.posts.size) %>
          </a>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>

    <div id="post-<%= post.id %>-likes" class="likes">
    </div>
    <div id="post-<%= post.id %>-comments" class="comments">
    </div>
    
    <%= render '/posts/post_commenting', :post=>post if can_comment?(post) %>

  </div>
  <div class="clear">
  </div>
</div>
<% if page_post_show? %>
<script>
  $('#post-<%= post.id %>-comments').load('/p/<%= post.id %>/ajax_comments');
</script>
<% end %>

app/views/posts/_post_commenting.html.erb
<div class="comment write_box">
<%#= " style='display:none'" if post.posts.size == 0 %>
<%# according to latest changes, this div should always be hidden %>

  <div class="comment-state-before">
    <%= text_area_tag '', T.t('page.post.actions.write_a_comment'), :rows=>1 %>
  </div>
  
  <div class="comment-state-during" style="display:none">
    <div class="comment-left">
      <%= my_image_tag cu_ro.p_, :dimensions=>32 %>
    </div>
    <div class="comment-right">
      
      <%= form_for post.posts.build, :url=>:create_comment_posts, :remote=>true, :html=>{:class=>'new_comment'} do |f| %>
        <%= f.hidden_field :post_id %>
        <%= f.text_area :body, :rows=>2 %>
        <div style="width:90%;">
          <%= content_tag :span, 196, :class=>"counter" %>
        </div>
      <% end %>
    </div>
    <div class="clear">
    </div>
  </div>

</div>

app/views/posts/_sidebar.html.erb
<%= background_image @user if @user %>
  <div class="in">  
    <div class="title no-link-decoration">
      <span class="icon-color action-reposta"></span>
      <%= link_to "Conta Verificada", profile_path(@user.username) %>
      <div class="clear">
      </div>
    </div>
    
    <%= content_tag :p, raw("#{content_tag(:strong, "User")} #{@user.username}") %>
    <%= content_tag :p, raw("#{content_tag(:strong, "Bio")} #{@user.bio}") %>
    <%= content_tag :p, raw("#{content_tag(:strong, "Web")} #{link_to @user.website_dots, @user.website, :target=>'_blank'}") %>
  </div>

app/views/posts/ajax_comments.html.erb
<script>registerContextMenu();</script>
<%= bitly %>
<%= render :partial => "/posts/comment", :collection => @comments %>

app/views/posts/ajax_likes.js.erb
<% content_for :html do %>
<div class="likes">
  <ul>
    <% @likes_users.each do |like_user| %>
      <li>
        <%= link_to my_image_tag(like_user.p_, :dimensions=>25), profile_path(like_user.username) %>
      </li>
    <% end %>
  </ul>
  <div class="clear">
  </div>
</div>
<% end %>
<% r = raw escape_javascript yield :html %>
s = "<%= r %>";
$("#<%= params[:update] %>").html(s);

app/views/posts/index.html.erb
<%= render '/posts/index' %>

app/views/posts/show.html.erb
<% content_for :jsload do %>
	//functions.profile.ajax.append_behaviour();
  functions.posts.ajax.append_behaviour();
  //functions.posts.more.append_behaviour();
  $title1 = $title2 = "<%= @post.body %>";
<% end %>
<%= render @post %>