config/routes.rb
Ex2::Application.routes.draw do

  get 'n' => "site#test"

  get "w/:text" => "google_search#search"

  get 'm' => 'mobile#index_posts', :as=>:mobile_root
  scope 'm', :as=>'mobile' do
    get "mentions"  => 'mobile#index_mentions'
    get 'posts'     => 'mobile#index_posts'
    post 'new_post' => 'mobile#index_new_post'
    get  "login" => 'mobile#login'
    post "login" => 'mobile#post_login'
    get "u/:username" => 'mobile#user', :as=>:user
    get "p/:id"            => 'mobile#post', :as=>:post
    post 'p/comment_create' => 'mobile#post_comment_create', :as=>:post_comment_create
    get "c/:label"  => 'mobile#city'
  end

  get 'c/:label' => 'cities#show', :as=>:city_label
  resources :cities, :only=>[:show] do
    collection do
      get 'base_search'
    end
  end

  scope 'a' do
    resources :smiles
    resources :user_agents, :only=>:index
    get 'user_sessions' => "user_sessions#index", :as=>'xxx'
    resources :translations, :path=>'t', :only=>[:index, :edit, :update] do
      collection do
        put   '' => 'translations#edit_multiple'
        post  '' => 'translations#update_multiple'
      end
    end
  end

  get 's/who_we_are' => 'site#who_we_are', :as => :s_who
  get 's/suggest' => 'suggestions#new', :as => :s_suggest
  

  resources :suggestions, :except => [:edit, :update]
  resources :user_sessions, :except => [:index, :edit, :update]
  
  get "u/out"    => "user_sessions#destroy",         :as => :out
  get "u/in"     => "user_sessions#new",             :as => :in
  get "u/new"    => redirect("r/new")
  
  get "u/send_password/:base64_key" => "user_sessions#send_password", :as =>:send_password
  get "u/new_password/:username/:token" => "user_sessions#new_password", :as =>:new_password
  post "u/create_password" => "user_sessions#create_password", :as =>:create_password

  get   "r/new"       => "registration#new"
  get   "r/new"       => "registration#new",          :as => :new
  post  "r/new"       => "registration#new_post"
  get   "r/captcha"   => "registration#captcha"
  post  "r/captcha"   => "registration#captcha_post"
  
  get "r/after_register"           => "registration#after_register"
=begin
  get "registration/new_by_profile"
  get "registration/new_by_invitation"
  get "registration/new_by_profile_post"
  get "registration/new_by_invitation_post"
  get "registration/confirm_email"
  get "registration/new_password"
  get "registration/new_password_post"

=end
  get  "e/basic"    => "edit#basic"
  put  "e/basic"    => "edit#basic_put"
  get  "e/cities"   => "edit#cities"
  put  "e/cities"   => "edit#cities_put"
  get  "e/username" => "edit#username"
  put  "e/username" => "edit#username_put"
  get  "e/email"    => "edit#email"
  put  "e/email"    => "edit#email_put"
  get  "e/password" => "edit#password"
  put  "e/password" => "edit#password_put"
  
  get  "e/photo" => "edit#photo"
  post "e/photo" => "edit#photo_post"
  
  get  "e/theme" => "edit#theme"
  post "e/theme" => "edit#theme_post"
=begin
  constraints :subdomain => "m" do
    get "s(/:text)"                 => "site#mobile_search"
    get "s/posts/:post_type/:text"  => "site#mobile_posts"
    root :to                        => "home#mobile_index"
  end
=end
  root :to => "home#index"

=begin
  get "search/paginated"
  get "search/async_holder"
  get "search/async_ajax"
=end

  get "s(/:text)" => "search#async", :as => :s
  get "s/posts/:post_type/:text" => "search#posts", :as => :search_posts
  get "z(/:text)" => "search#paginated"
  get "h/posts_followings_all_latest" => "home#posts_followings_all_latest"
  get "h/posts_followings_all"    => "home#posts_followings_all"
  get "h/posts_followings_status" => "home#posts_followings_status",  :filter => Post::CATEGORY_STATUS
  get "h/posts_followings_image"  => "home#posts_followings_image",   :filter => Post::CATEGORY_IMAGE
  get "h/posts_followings_audio"  => "home#posts_followings_audio",   :filter => Post::CATEGORY_AUDIO
  get "h/posts_followings_other"  => "home#posts_followings_other",   :filter => Post::CATEGORY_OTHER
  get "h/posts_followers"         => "home#posts_followers"
  get 'h/ajax_notifications'           => "home#ajax_notifications"
  get 'h/ajax_news_button'        => "home#ajax_news_button"
  post 'h/invite'           => "home#invite"
  post 'h/mark_notifications_as_read'           => "home#mark_notifications_as_read"
  get 'h/ajax_suggestions_sidebar'  => 'users#ajax_suggestions_sidebar', :as=> :user_ajax_suggestions_sidebar
  

  resources :posts, :path => "p", :only => [:show, :destroy] do
    get "ajax_likes"
    post "like"
    get "ajax_comments"
    collection do
      get "generate_notifications"
      post "create_status"
      post "create_image"
      post "create_comment"
      get "ajax_search"
    end
  end
=begin
  devise_for :users do
    get "/u/out" => "devise/sessions#destroy",  :as => :out
    get "/u/new" => "devise/registrations#new", :as => :new
    get "/u/in"  => "devise/sessions#new",      :as => :in
  end
=end
  
  resources :users, :path => "u" do#, :only =>[:show, :index] do #, :index, :update do
    get :ajax_posts_all
    get :ajax_posts_status,  :filter => :status
    get :ajax_posts_image,   :filter => :image

    get :ajax_relations_following,  :filter => :following
    get :ajax_relations_follower,   :filter => :follower
    get :ajax_relations_friend,     :filter => :friend
    
    get :ajax_relations_sidebar_friend,     :filter => :friend
    
    get :likes
    get :ajax_relate_panel
    put :ajax_relate
  end
  get ":username" => "users#show", :as => "profile", :constraints => { :username => User::USERNAME_REGEX }
  scope ":username", :constraints => { :username => User::USERNAME_REGEX } do
    get 'followings'  => "relations#followings",  :as => :username_followings
    get 'followers'   => "relations#followers",   :as => :username_followers
    get 'friends'     => "relations#friends",     :as => :username_friends
  end

end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
  belongs_to :user

  attr_accessor :key, :password
  
  validate :custom_validations

  def custom_validations
    #errors.add(:username, "username is not valid or is already taken") unless User.username_allowed username
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

=begin
  def after_login
    (cookies[:interesting_user_ids] || '').split(',').each do |interesting_user_id|
      Relation.relate_users(current_user, interesting_user_id, :suggggggggggggggest_follow)
    end
    current_user.recount_relations
    cookies[:interesting_user_ids] = nil
    render :nothing=>true
  end
=end

  #caches_action :send_password, :expires_in => 1.day
  def send_password
    key = Base64.urlsafe_decode64(params[:base64_key]) rescue ''
    @user = User.findk(key)
    return render :text=>"usuario nao encontrado" unless @user
    a,b = @user.email.split('@')
    @email_view = "#{a[0..2]}...@#{b}"
    @email_server = "http://#{b}"
    @new_password_token = MyF.md5(@user.authentication_token)
    MyM.forgot_password(@user, @new_password_token).deliver
  end

  def new_password
    @user = User.findu(params[:username])
    return render :text=>"usuario nao encontrado" unless @user
    return render :text=>"este link invalido ou expirou, gere-o novamente" unless params[:token] == MyF.md5(@user.authentication_token)
  end

  def create_password
    #@user = User.findu(params[:username])
    #return render :text=>"usuario nao encontrado" unless @user
    #return render :text=>"este link invalido ou expirou, gere-o novamente" unless params[:token] == MyF.md5(@user.authentication_token)
    new_password
    return render :new_password unless @user.save_password(params[:password])
    @user.login
    session[:user_session] = {:id=>@user.id, :auth_token =>@user.authentication_token}
    redirect_to(:root)
  end

  # GET /user_sessions
  # GET /user_sessions.xml
  def index
    @user_sessions = UserSession.order("updated_at DESC")
  end

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    p = params[:user_session]
    @user = User.findk(p[:key])
    @user_session_found = !!@user
    if @user and @user.check_password?(p[:password])
      @user.login
      #session[:current_user_id] = @user.id
      session[:user_session] = {:id=>@user.id, :auth_token =>@user.authentication_token}
      UserAgent.note(request.user_agent)
      redirect_to(:root)
    else
      @user_session = UserSession.new :key => p[:key]
      render :action => "new"
    end
  end
  
  # PUT /user_sessions/1
  # PUT /user_sessions/1.xml
  def update
  
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    if current_user
      #UserSession.delete_all(:authentication_token => session[:user_session][:authentication_token])
      current_user.logout
      session[:user_session] = nil
    end
    #session[:current_user_id] = nil
    redirect_to :new
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>auth user</th>
    <th>auth session</th>
    <th>last activity</th>
    <% if false %>
    <th></th>
    <% end %>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= link_to user_session.user.username_at, profile_path(user_session.user.username), :target=>'_blank' %></td>
    <td><%= user_session.user.email %></td>
    <td><%= user_session.user.authentication_token[0..5] %>...</td>
    <td><%= user_session.authentication_token[0..5] %>...</td>
    <td><%= l user_session.updated_at, :format => :short %></td>
    <% if false %>
    <td><%#= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/user_sessions/new.html.erb
<style>
  #inside .input-type-text { font-size:14px;line-height:18px;padding:3px;border: #ccc solid 1px;margin-bottom:10px }
  #inside label { font-size:16px;color:#333; }
  #inside .ui-button { font-weight:bold; }
</style>

<div id="inside" style="display:inline-block;width:100%;">
<div style="width:600px;margin:100px auto;display:block;background:#fff;border-radius:20px;padding:20px">

  <%= form_for(@user_session, :html=>{:style=>"margin:0 auto"}) do |f| %>
    <% if @user_session.errors.any? %>
      <div id="error_explanation">
        <ul>
        <% @user_session.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :username, "#{T.t('subheader.login.field1')}:" %><br />
      <%= f.text_field :key %>
      <% if @user_session_found %>
        <%= link_to "Send My Password to My E-mail Address", send_password_path(Base64.urlsafe_encode64(@user_session.key)), :class=>"ui-button" %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :password, "#{T.t('subheader.login.field2')}:" %><br />
      <%= f.password_field :password %>
    </div>
    <div class="actions">
      <%= f.submit "Sign In", :class=>"ui-button" %>
    </div>
  <% end %>


</div>
</div>

app/views/user_sessions/new_password.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this form from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_tag :create_password do %>
  <%= hidden_field_tag :token, params[:token] %>
  <%= hidden_field_tag :username, params[:username] %>
  <%= content_tag :p, "email: #{@user.email}" %>
  <%= content_tag :p, "username: #{@user.username}" %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag %>
<% end %>

app/views/user_sessions/send_password.html.erb
<div style="margin-bottom:200px;padding-top:100px;">
<center>Sua senha foi enviada para o email abaixo :)</center>
<h1><center><strong><%= @email_view %></strong></center></h1>
<br/>
<center>acesse <%= link_to @email_server, @email_server, :target=>'_blank', :style=>"font-size:20px;" %> agora</center>
<%= link_to "link do email", new_password_url(@user.username.downcase, @new_password_token) unless Rails.env.production? %>
</div>